"use client";

import { Download } from "lucide-react";

interface ExportButtonProps {
  content: string;
  filename: string;
  label?: string;
}

export function ExportButton({ content, filename, label }: ExportButtonProps) {
  const handleExport = () => {
    const htmlContent = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${filename}</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 48px 64px; max-width: 900px; margin: 0 auto; color: #1a1a2e; line-height: 1.7; }
h1 { font-size: 2rem; margin-bottom: 8px; color: #0f172a; }
h2 { font-size: 1.4rem; margin-top: 32px; margin-bottom: 12px; color: #1e293b; border-bottom: 2px solid #6366f1; padding-bottom: 6px; }
h3 { font-size: 1.1rem; margin-top: 24px; margin-bottom: 8px; color: #334155; }
p { margin-bottom: 12px; }
ul, ol { padding-left: 24px; margin-bottom: 16px; }
li { margin-bottom: 6px; }
table { border-collapse: collapse; width: 100%; margin: 16px 0; }
th, td { border: 1px solid #e2e8f0; padding: 10px 14px; text-align: left; }
th { background: #f1f5f9; font-weight: 600; }
strong { color: #0f172a; }
.header { border-bottom: 3px solid #6366f1; padding-bottom: 16px; margin-bottom: 32px; }
.header small { color: #6366f1; font-weight: 500; }
.footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 0.85rem; color: #94a3b8; }
@media print { body { padding: 24px; } }
</style>
</head>
<body>
<div class="header">
<small>Neuromart.ai — Executive Report</small>
<br><small>${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</small>
</div>
${convertMarkdownToHTML(content)}
<div class="footer">
Generated by Neuromart.ai Executive Suite
</div>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${filename}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleExport}
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        padding: "6px 12px",
        borderRadius: 8,
        border: "1px solid var(--border)",
        background: "var(--bg-tertiary)",
        color: "var(--text-secondary)",
        fontSize: "0.75rem",
        cursor: "pointer",
        transition: "all 0.15s",
        marginTop: 8,
      }}
    >
      <Download size={12} />
      {label || "Export"}
    </button>
  );
}

function convertMarkdownToHTML(md: string): string {
  return md
    .replace(/^### (.*$)/gm, "<h3>$1</h3>")
    .replace(/^## (.*$)/gm, "<h2>$1</h2>")
    .replace(/^# (.*$)/gm, "<h1>$1</h1>")
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.*?)\*/g, "<em>$1</em>")
    .replace(/^- (.*$)/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, "<ul>$&</ul>")
    .replace(/\n{2,}/g, "</p><p>")
    .replace(/^(?!<[hulo])/gm, "<p>")
    .replace(/(?<![>])$/gm, "</p>");
}
