import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import OpenAI from "openai";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { agents, getAllAgents } from "@/lib/agents";

function getAnthropicClient() {
  return new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! });
}
function getOpenAIClient() {
  return new OpenAI({ apiKey: process.env.OPENAI_API_KEY! });
}
function getGeminiClient() {
  return new GoogleGenerativeAI(process.env.GOOGLE_API_KEY!);
}

const DIGEST_PROMPT = `Provide your weekly executive briefing for Dr. Abiy Selassie, founder of Neuromart.ai.

Format your response EXACTLY as:
## Top 3 Priorities This Week
1. [Priority with specific action]
2. [Priority with specific action]
3. [Priority with specific action]

## Key Metrics to Watch
- [Metric 1]
- [Metric 2]

## Risks & Blockers
- [Any concerns]

## Recommendation
[Your #1 recommendation for the founder this week]

Keep it under 300 words. Be specific, not generic. Reference actual Neuromart.ai products and verticals.`;

async function getExecDigest(agentId: string): Promise<string> {
  const agent = agents[agentId];
  if (!agent) return "";

  if (agent.provider === "anthropic") {
    const res = await getAnthropicClient().messages.create({
      model: agent.model, max_tokens: 1500,
      system: agent.systemPrompt,
      messages: [{ role: "user", content: DIGEST_PROMPT }],
    });
    const block = res.content[0];
    return block.type === "text" ? block.text : "";
  } else if (agent.provider === "google") {
    const model = getGeminiClient().getGenerativeModel({ model: agent.model });
    const chat = model.startChat({
      history: [
        { role: "user", parts: [{ text: "System: " + agent.systemPrompt }] },
        { role: "model", parts: [{ text: "Understood." }] },
      ],
    });
    const result = await chat.sendMessage(DIGEST_PROMPT);
    return result.response.text();
  } else {
    const res = await getOpenAIClient().chat.completions.create({
      model: agent.model, max_tokens: 1500,
      messages: [
        { role: "system", content: agent.systemPrompt },
        { role: "user", content: DIGEST_PROMPT },
      ],
    });
    return res.choices[0]?.message?.content || "";
  }
}

export async function POST(req: NextRequest) {
  const { sendEmail } = await req.json();

  try {
    const allExecs = getAllAgents();
    const digests = await Promise.all(
      allExecs.map(async (agent) => {
        const content = await getExecDigest(agent.id);
        return { agentId: agent.id, name: agent.name, title: agent.title, content };
      })
    );

    const date = new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
    const fullDigest = `# Neuromart.ai Weekly Executive Digest\n**${date}**\n\n---\n\n` +
      digests.map((d) => `# ${d.name} — ${d.title}\n\n${d.content}`).join("\n\n---\n\n") +
      "\n\n---\n*Generated by Neuromart.ai ExecSuite*";

    // Optionally send via email
    if (sendEmail && process.env.RESEND_API_KEY) {
      const senderEmail = process.env.SENDER_EMAIL || "onboarding@resend.dev";
      const founderEmail = process.env.FOUNDER_EMAIL || sendEmail;

      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          from: `Neuromart.ai ExecSuite <${senderEmail}>`,
          to: [founderEmail],
          subject: `Weekly Exec Digest — ${date}`,
          html: `<pre style="font-family: -apple-system, sans-serif; white-space: pre-wrap; max-width: 700px; margin: 0 auto; padding: 32px; line-height: 1.6;">${fullDigest.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>`,
        }),
      });
    }

    return NextResponse.json({ digest: fullDigest, executives: digests });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Digest generation failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
